### ISSUE TITLE
时隔项目发布4个多月，打破零回复惨案，对此项目库有个小问题问下扑克佬

### ISSUE THREAD

**Issue by P3R5T7U9** [Poker-sang/DanmakuPlayer#1]
今天才翻到这个项目库，所有文件翻了个遍，也没翻到成品，不知此项目库的成品是需按照扑克佬你在此项目库的readme文件末尾所附的联系方式，加上扑克佬你的好友后，付费购买成品么？？😖

**Comment by Poker-sang** [comment]
不是的不是的，只是这个我现在还经常更新所以没有发发行版，这个是开源项目可以免费用的，也可以自己改代码】(｀・ω・´)
你需要的话加我我可以编译一份给你

**Comment by P3R5T7U9** [comment]
> 不是的不是的，只是这个我现在还经常更新所以没有发发行版，这个是开源项目可以免费用的，也可以自己改代码】(｀・ω・´) 你需要的话加我我可以编译一份给你

抱歉回复迟了，扑克大，昨晚我由于忙着解决一问题，都没注意到github以邮件提醒形式推送扑克大你在深夜10点多发的回复，直到刚刚才看到😖

既然扑克大你回复可以编译一份分享给我，那麻烦扑克大将成品发到我的邮箱：lws226691zhao@163.com 这个地址了，先感谢扑克大了
(小声：主要一直没接触过C艹，⑧懂如何对用C艹编写的项目进行编译😭)

**Comment by Poker-sang** [comment]
🤔但是这是C#写的啊

**Comment by bsdayo** [comment]
🤔但是这是C#写的啊

**Comment by P3R5T7U9** [comment]
> 🤔但是这是C#写的啊

@Poker-sang @bsdayo 抱歉我又回复迟了，没想到我开的这个issue 将bs佬都引来了，我昨晚发的那条求扑克佬帮忙编译成品的评论提到的C艹，就是指C Shrip(也即C#)，介不是咱国内业界对C#称呼统一的绰号么？？🤔
(小声：虽说这个称呼是不正确的，但我已然叫习惯了😂)

另外，我翻找昨晚收到的邮件，已看到扑克大你发送的邮件所附的成品，辛苦惹，特此感激不尽
(再次小声：像扑克大这种不厌我烦，在回复中贴心问是否需要帮忙编译成品，像扑克大这种好心的大佬，业界已不多啦ʕ ᵔᴥᵔ ʔ)

**Comment by Poker-sang** [comment]
C艹一般是C++的说
另外要是没事了的话我就把issue关了喔

**Comment by P3R5T7U9** [comment]
> C艹一般是C++的说 另外要是没事了的话我就把issue关了喔

啊这(，是我认知出错了么，之前在破站上看到几位关注已久一直用C#写项目的大佬，他们经常将C#称呼为C艹，说是“#”这个字符形似“艹”😓

另外，由于近几天有些忙，我在昨晚才注意到扑克大你发的含成品的回复邮件，由于时间关系，想着早上起来再下载到本地进行测试，我先主动关闭这个issue，等之后实测过程中出现一些bug，再来这个issue底下向扑克大你反馈
